apiVersion: v1
kind: Service
metadata:
  name: karma-service
  namespace: karma
spec:
  selector:
    app: karma
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30085